package MyServer.MyServicePackage;

/**
* MyServer/MyServicePackage/DTRSExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public final class DTRSExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MyServer.MyServicePackage.DTRSException value = null;

  public DTRSExceptionHolder ()
  {
  }

  public DTRSExceptionHolder (MyServer.MyServicePackage.DTRSException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyServer.MyServicePackage.DTRSExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyServer.MyServicePackage.DTRSExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyServer.MyServicePackage.DTRSExceptionHelper.type ();
  }

}
