package MyServer.MyServicePackage;


/**
* MyServer/MyServicePackage/DTRSException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public final class DTRSException extends org.omg.CORBA.UserException
{

  public DTRSException ()
  {
    super(DTRSExceptionHelper.id());
  } // ctor


  public DTRSException (String $reason)
  {
    super(DTRSExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class DTRSException
