package MyServer;


/**
* MyServer/MyService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public interface MyService extends MyServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyService
