package MyServer;


/**
* MyServer/MyServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public class MyServicePOATie extends MyServicePOA
{

  // Constructors

  public MyServicePOATie ( MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public MyServicePOATie ( MyServer.MyServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public MyServer.MyServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (MyServer.MyServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int getUDPPort () throws MyServer.MyServicePackage.DTRSException
  {
    return _impl.getUDPPort();
  } // getUDPPort

  public void initializeBoxOffice (String boxOffice) throws MyServer.MyServicePackage.DTRSException
  {
    _impl.initializeBoxOffice(boxOffice);
  } // initializeBoxOffice

  public String getBoxOffice ()
  {
    return _impl.getBoxOffice();
  } // getBoxOffice

  public String printBoxOfficeRecords (int customerID)
  {
    return _impl.printBoxOfficeRecords(customerID);
  } // printBoxOfficeRecords

  public void reserve (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException
  {
    _impl.reserve(customerID, showID, numberOfTickets);
  } // reserve

  public void cancel (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException
  {
    _impl.cancel(customerID, showID, numberOfTickets);
  } // cancel

  public int check (String showID)
  {
    return _impl.check(showID);
  } // check

  public void exchange (int customerID, String reservedShowID, int reservedTickets, String desiredShowID, int desiredTickets) throws MyServer.MyServicePackage.DTRSException
  {
    _impl.exchange(customerID, reservedShowID, reservedTickets, desiredShowID, desiredTickets);
  } // exchange

  public boolean canExchange (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException
  {
    return _impl.canExchange(customerID, showID, numberOfTickets);
  } // canExchange

  private MyServer.MyServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MyServicePOATie
