package MyServer;


/**
* MyServer/MyServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

abstract public class MyServiceHelper
{
  private static String  _id = "IDL:MyServer/MyService:1.0";

  public static void insert (org.omg.CORBA.Any a, MyServer.MyService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MyServer.MyService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MyServer.MyServiceHelper.id (), "MyService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MyServer.MyService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MyServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MyServer.MyService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MyServer.MyService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MyServer.MyService)
      return (MyServer.MyService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MyServer._MyServiceStub stub = new MyServer._MyServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MyServer.MyService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MyServer.MyService)
      return (MyServer.MyService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MyServer._MyServiceStub stub = new MyServer._MyServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
