package MyServer;


/**
* MyServer/MyServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public interface MyServiceOperations 
{
  int getUDPPort () throws MyServer.MyServicePackage.DTRSException;
  void initializeBoxOffice (String boxOffice) throws MyServer.MyServicePackage.DTRSException;
  String getBoxOffice ();
  String printBoxOfficeRecords (int customerID);
  void reserve (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException;
  void cancel (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException;
  int check (String showID);
  void exchange (int customerID, String reservedShowID, int reservedTickets, String desiredShowID, int desiredTickets) throws MyServer.MyServicePackage.DTRSException;
  boolean canExchange (int customerID, String showID, int numberOfTickets) throws MyServer.MyServicePackage.DTRSException;
} // interface MyServiceOperations
