package MyServer;

/**
* MyServer/MyServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Terri-Anne/Desktop/workspace-classic/DTRSCorbaAssignment/simple.idl
* Friday, November 4, 2011 4:25:21 PM PDT
*/

public final class MyServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public MyServer.MyService value = null;

  public MyServiceHolder ()
  {
  }

  public MyServiceHolder (MyServer.MyService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyServer.MyServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyServer.MyServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyServer.MyServiceHelper.type ();
  }

}
